### ISSUE TITLE
ERROR could not retrieve mbeans

### ISSUE THREAD

**Issue by chipgata** [amient/kafka-metrics#19]
My kafka cluster version: 0.10.1.1
kafka-metrics: master branch
I used
Example usage for remote Kafka cluster with Metrics Agent

On the Kafka Cluster:

> ./discovery/build/scripts/discovery \
>     --zookeeper "<SEED-ZK-HOST>:<ZK-PORT>" \
>     --dashboard "remote-kafka-cluster" \
>     --topic "metrics" | ./metrics-agent/build/scripts/metrics-agent

On the Kafka Metrics instance:

> ./discovery/build/scripts/discovery \
>     --zookeeper "<SEED-ZK-HOST>:<ZK-PORT>" \
>     --topic "metrics" \
>     --dashboard "remote-kafka-cluster" \
>     --dashboard-path "./.data/grafana/dashboards" \

and give the errors:

```
ERROR could not retrieve mbeans (io.amient.kafka.metrics.JMXScannerTask:116) 
javax.management.InstanceNotFoundException: kafka.server:type=Fetch,client-id=console-consumer-52018
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBeanInfo(DefaultMBeanServerInterceptor.java:1375)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getMBeanInfo(JmxMBeanServer.java:920)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1462)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getMBeanInfo(RMIConnectionImpl.java:905)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:276)
```

**Comment by michal-harish** [comment]
There is one more problem which I have discovered but not related to this - the queries from grafana don't work for influxdb relative time that inlucdes 'now'.
