### ISSUE TITLE
JMX Scanner has a problem with some MBeans exposed by Kafka 0.8.x

### ISSUE THREAD

**Issue by michal-harish** [amient/kafka-metrics#3]
WARN could not cast kafka.log:type=Log,name=LogStartOffset,topic=...,partition=.. into double value  (io.amient.kafka.metrics.JMXScannerTask:147)
javax.management.RuntimeMBeanException: java.util.NoSuchElementException
...
at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:906)
	at io.amient.kafka.metrics.JMXScannerTask.extractMeasurements(JMXScannerTask.java:143)
	at io.amient.kafka.metrics.JMXScannerTask.run(JMXScannerTask.java:107)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
...

**Comment by michal-harish** [comment]
Caused by a particular MBean in Kafka 0.8:
Caused by: java.util.NoSuchElementException
	at java.util.concurrent.ConcurrentSkipListMap$Iter.advance(ConcurrentSkipListMap.java:2299)
	at java.util.concurrent.ConcurrentSkipListMap$ValueIterator.next(ConcurrentSkipListMap.java:2326)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.IterableLike$class.head(IterableLike.scala:107)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at kafka.log.Log.logStartOffset(Log.scala:502)
	at kafka.log.Log$$anon$2.value(Log.scala:86)
	at kafka.log.Log$$anon$2.value(Log.scala:85)
	at com.yammer.metrics.reporting.JmxReporter$Gauge.getValue(JmxReporter.java:63)
